# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 65) do

  create_table "app_setting", :force => true do |t|
    t.string   "name"
    t.string   "value"
    t.text     "description"
    t.datetime "updated_at"
    t.string   "field_type",  :default => "text_field"
  end

  create_table "article", :force => true do |t|
    t.string   "title"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "case_columns_setting", :force => true do |t|
    t.integer "sfcontact_setting_id"
    t.boolean "your_component__c",                :default => true
    t.boolean "your_sfuser___last_name",          :default => true
    t.boolean "your_sf_type",                     :default => true
    t.boolean "your_customer_priority__c",        :default => true
    t.boolean "your_sfcase___created_date",       :default => true
    t.boolean "your_sfcase___last_updated__c"
    t.boolean "your_sfcontact___last_name",       :default => false
    t.boolean "your_expected_resolution_date__c", :default => false
    t.boolean "all_component__c",                 :default => true
    t.boolean "all_sfuser___last_name",           :default => true
    t.boolean "all_sf_type",                      :default => true
    t.boolean "all_customer_priority__c",         :default => true
    t.boolean "all_sfcase___created_date",        :default => true
    t.boolean "all_sfcase___last_updated__c"
    t.boolean "all_sfcontact___last_name",        :default => false
    t.boolean "all_expected_resolution_date__c",  :default => false
    t.boolean "your_cr_status__c",                :default => false
    t.boolean "all_cr_status__c",                 :default => false
    t.boolean "your_expedited_priority__c"
    t.boolean "your_contact_id"
    t.boolean "your_customer_tracking__c"
    t.boolean "your_weekly_notes__c"
    t.boolean "all_expedited_priority__c"
    t.boolean "all_contact_id"
    t.boolean "all_customer_tracking__c"
    t.boolean "all_weekly_notes__c"
    t.boolean "your_tag__c"
    t.boolean "all_tag__c"
    t.boolean "your_cr_number__c"
    t.boolean "all_cr_number__c"
  end

  create_table "case_view_setting", :force => true do |t|
    t.string  "sfcontact_setting_id"
    t.text    "status"
    t.boolean "viewable",             :default => true
  end

  create_table "error", :force => true do |t|
    t.string   "sf_id"
    t.string   "sf_entity"
    t.string   "sql_entity"
    t.text     "error_message"
    t.datetime "created_time"
    t.text     "other_information"
    t.datetime "last_modified"
  end

  create_table "page", :force => true do |t|
    t.string   "name"
    t.string   "controller"
    t.string   "action"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "rails_cron", :force => true do |t|
    t.text    "command"
    t.integer "start"
    t.integer "finish"
    t.integer "every"
    t.boolean "concurrent"
    t.string  "interval_string"
  end

  create_table "rating", :force => true do |t|
    t.integer "one",           :default => 0
    t.integer "two",           :default => 0
    t.integer "three",         :default => 0
    t.integer "four",          :default => 0
    t.string  "sfsolution_id"
  end

  create_table "refresh_cache", :force => true do |t|
    t.string   "refreshable_type"
    t.string   "refreshable_id"
    t.datetime "created_at"
  end

  create_table "sfaccount", :force => true do |t|
    t.string   "name"
    t.string   "sf_type"
    t.string   "parent_id"
    t.string   "billing_street"
    t.string   "billing_city"
    t.string   "billing_state"
    t.string   "billing_postal_code"
    t.string   "billing_country"
    t.string   "shipping_street"
    t.string   "shipping_city"
    t.string   "shipping_state"
    t.string   "shipping_postal_code"
    t.string   "shipping_country"
    t.string   "phone"
    t.string   "fax"
    t.string   "website"
    t.text     "description"
    t.string   "site"
    t.string   "owner_id"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "host_id__c"
    t.string   "sales_region__c"
    t.string   "dun_snumber__c"
    t.string   "tam_front_end_seats__c"
    t.string   "tam_back_end_seats__c"
    t.string   "customer_id__c"
    t.string   "address_issue__c"
    t.string   "credit_rating__c"
    t.string   "nda__c"
    t.string   "nda_description__c"
    t.string   "customer_support_alias__c"
    t.string   "sap_sync_status__c"
    t.string   "sap_payment_terms__c"
    t.string   "sap_account_group__c"
    t.string   "lead_ae_email__c"
    t.string   "sap_sales_districts__c"
    t.string   "sap_customer_id__c"
    t.string   "tsmc_lib_nda_front_end__c"
    t.string   "sap_legacy_id__c"
    t.string   "sla__c"
    t.string   "initial_sap_upload__c"
    t.date     "nda_expiration_date__c"
    t.string   "tsmc_lib_nda_complete__c"
    t.string   "credit_score__c"
    t.string   "entity_type__c"
    t.date     "credit_score_updated__c"
    t.text     "activities__c"
    t.string   "dns_domain__c"
    t.string   "allow_molten__c"
    t.string   "toll_free_phone__c"
    t.string   "account_type_code__c"
    t.string   "sap_org_id__c"
    t.string   "sf_id",                      :default => "", :null => false
    t.string   "type"
    t.string   "sap_log_id__c"
    t.string   "vat__c"
    t.string   "sap_shipping_account_id__c"
    t.string   "email_flyer__c"
    t.string   "last_activity_date"
    t.string   "sap_customer_tax_group__c"
    t.string   "portal_default_type__c"
    t.string   "portal_case_types__c"
    t.string   "portal_case_scope__c"
    t.string   "industry"
    t.string   "annual_revenue"
    t.string   "currency_iso_code"
    t.string   "is_deleted"
    t.string   "master_record_id"
  end

  add_index "sfaccount", ["sf_id"], :name => "sfaccount_sf_id_idx", :unique => true
  add_index "sfaccount", ["sf_id"], :name => "index_sfaccount_on_sf_id"

  create_table "sfattach", :force => true do |t|
    t.string   "parent_id"
    t.string   "name"
    t.string   "is_private"
    t.string   "content_type"
    t.integer  "body_length"
    t.text     "body"
    t.string   "owner_id"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "sf_id",               :default => "", :null => false
    t.string   "is_deleted"
  end

  add_index "sfattach", ["sf_id"], :name => "sfattach_sf_id_idx", :unique => true
  add_index "sfattach", ["parent_id"], :name => "index_sfattach_on_parent_id"

  create_table "sfcase", :force => true do |t|
    t.integer  "case_number"
    t.string   "contact_id"
    t.string   "asset_id"
    t.string   "supplied_name"
    t.string   "supplied_email"
    t.string   "supplied_phone"
    t.string   "supplied_company"
    t.string   "sf_type"
    t.string   "record_type_id"
    t.string   "status"
    t.string   "origin"
    t.string   "is_visible_in_self_service"
    t.string   "subject"
    t.string   "priority"
    t.text     "description"
    t.string   "is_closed"
    t.datetime "closed_date"
    t.string   "is_escalated"
    t.string   "owner_id"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "quart_formal__c"
    t.string   "clarify_id__c"
    t.string   "originator__c"
    t.string   "customer_priority__c"
    t.string   "operating_system__c"
    t.string   "reproducible__c"
    t.string   "component__c"
    t.string   "customer_tracking__c"
    t.string   "query_build_view__c"
    t.string   "dataor_test_case_provided__c"
    t.string   "design_geometryn_m__c"
    t.string   "foundry__c"
    t.string   "cell_count_k_objects__c"
    t.string   "speed_m_hz__c"
    t.string   "scopeof_flow__c"
    t.string   "formal_verification__c"
    t.string   "qualityof_results__c"
    t.string   "hdl__c"
    t.string   "test_case_path__c"
    t.string   "std_cell_library__c"
    t.date     "tape_out_date__c"
    t.string   "synthesis_tool__c"
    t.string   "schedule_status__c"
    t.string   "time_stamp_build__c"
    t.string   "version_number__c"
    t.string   "noise_signoff__c"
    t.string   "power_signoff__c"
    t.string   "clarify_customer__c"
    t.string   "analysis_tool__c"
    t.string   "target_release__c"
    t.date     "clarify_create_date__c"
    t.string   "program_area__c"
    t.string   "expedited_priority__c"
    t.date     "target_fast_track_build__c"
    t.date     "estimated_start_date__c"
    t.date     "estimated_finish_date__c"
    t.string   "test_case_provided__c"
    t.string   "customer_visible__c"
    t.string   "opportunity_name__c"
    t.date     "requested_start_date__c"
    t.date     "requested_end_date__c"
    t.string   "initial_quality_of_results__c"
    t.float    "initial_util__c"
    t.string   "palace_options_used__c"
    t.string   "initial_speed__c"
    t.string   "design_top_level_name__c"
    t.string   "mode__c"
    t.string   "number_of_clocks__c"
    t.string   "number_of_design_blocks__c"
    t.string   "power_analysis_tool__c"
    t.string   "tape_out_limiting__c"
    t.string   "sales_opportunity_related__c"
    t.string   "benmark_impacted__c"
    t.string   "special_situation__c"
    t.string   "special_situation_desc__c"
    t.string   "benchmark_case__c"
    t.string   "product__c"
    t.string   "is_closeable__c"
    t.string   "schedule_comments__c"
    t.string   "shadow_status__c"
    t.string   "code_streams_priority__c"
    t.string   "tag__c"
    t.string   "engineer_assigned__c"
    t.string   "logic_verification__c"
    t.string   "physical_verification__c"
    t.string   "extraction__c"
    t.string   "timing_signoff__c"
    t.string   "dft__c"
    t.date     "expected_build_date__c"
    t.string   "man_hours_of_effort__c"
    t.string   "workaround_description__c"
    t.string   "workaround_available__c"
    t.string   "needs_docs__c"
    t.string   "target_releases__c"
    t.date     "expected_resolution_date__c"
    t.string   "fix_version__c"
    t.string   "cr_list_id__c"
    t.string   "crash_details__c"
    t.string   "description_notes__c"
    t.string   "tech_campaign_id__c"
    t.string   "release_note__c"
    t.string   "tech_campaign2_id__c"
    t.string   "r_d_submission__c"
    t.string   "pe_owner_user_id__c"
    t.string   "component_link_id__c"
    t.string   "aging_weeks__c"
    t.string   "internal_comments__c"
    t.string   "committed__c"
    t.float    "level_of_effort__c"
    t.string   "sf_id",                                      :default => "", :null => false
    t.string   "type"
    t.string   "sql_sync_id__c"
    t.string   "pe_checkpoint_id__c"
    t.string   "status_1_stream__c"
    t.string   "status_2_stream__c"
    t.string   "status_3_stream__c"
    t.string   "x1st_stream__c"
    t.string   "x2nd_stream__c"
    t.string   "x3rd_stream__c"
    t.string   "weekly_notes__c"
    t.string   "tech_campaign_task_id__c"
    t.string   "due_date__c"
    t.string   "has_comments_unread_by_owner"
    t.string   "has_css_comments"
    t.string   "fast_track_required__c"
    t.string   "target_analysis_done__c"
    t.string   "target_fix_available__c"
    t.string   "target_fix_merged__c"
    t.string   "actual_analysis_done__c"
    t.string   "actual_fix_available__c"
    t.string   "actual_fix_merged__c"
    t.string   "actual_fix_to_scm__c"
    t.string   "target_fix_stream__c"
    t.string   "cr_status__c"
    t.string   "customer_account_id__c"
    t.string   "related_documentation_completed__c"
    t.string   "reason_for_urgent_and_critical_priority__c"
    t.string   "committed_finish_date__c"
    t.string   "delta_commit_to_actual__c"
    t.string   "committed_fix_date__c"
    t.string   "delta_expected_to_commit__c"
    t.string   "r_d_first_owner__c"
    t.string   "currency_iso_code"
    t.string   "first_support_owner__c"
    t.string   "reason"
    t.string   "account_id"
    t.string   "is_deleted"
    t.string   "has_self_service_comments"
    t.string   "parent_id"
    t.string   "r_d_owner_id__c"
    t.string   "branch_name__c"
    t.string   "estimated_effort__c"
    t.string   "internal_release_number__c"
    t.string   "external_release_number__c"
    t.string   "other__c"
    t.string   "fixed_version__c"
    t.datetime "last_updated__c"
    t.string   "critical_date__c"
    t.string   "latest_scm_or_ft_build_tested_against__c"
    t.string   "last_modified_age__c"
    t.string   "task_force__c"
    t.string   "cr_number__c"
    t.string   "parent_case_id__c"
    t.string   "release_notes_documentation__c"
    t.string   "unit_system_test_details__c"
    t.string   "tech_pubs_completed__c"
    t.string   "cc__c"
    t.string   "marketing_input__c"
  end

  add_index "sfcase", ["sf_id"], :name => "sf_id_idx", :unique => true
  add_index "sfcase", ["contact_id"], :name => "index_sfcase_on_contact_id"
  add_index "sfcase", ["sf_id"], :name => "index_sfcase_on_sf_id"

  create_table "sfcase_watcher", :force => true do |t|
    t.string   "sf_id"
    t.string   "owner_id"
    t.boolean  "is_deleted"
    t.string   "name"
    t.string   "currency_iso_code"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.date     "last_activity_date"
    t.string   "case_number_id__c"
    t.string   "case_fields_deferred__c"
    t.string   "tech_campaign_id__c"
    t.string   "user_id__c"
    t.string   "account_id__c"
    t.string   "case_fields__c"
    t.string   "case_scope__c"
    t.string   "component_id__c"
    t.string   "team_id__c"
  end

  create_table "sfcase_watcher_list", :force => true do |t|
    t.string   "sf_id"
    t.boolean  "is_deleted"
    t.string   "name"
    t.string   "currency_iso_code"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.date     "last_activity_date"
    t.string   "contact_id__c"
    t.string   "alias_email__c"
    t.string   "case_watcher_id__c"
    t.string   "email__c"
  end

  create_table "sfcatdata", :force => true do |t|
    t.string   "sf_id"
    t.string   "category_node_id"
    t.string   "s_object_id"
    t.string   "created_by_id"
    t.datetime "created_date"
    t.string   "last_modified_by_id"
    t.datetime "last_modified_date"
    t.datetime "system_modstamp"
    t.string   "related_sobject_id"
    t.string   "is_deleted"
  end

  add_index "sfcatdata", ["sf_id"], :name => "sfcatdata_sf_id_idx", :unique => true
  add_index "sfcatdata", ["sf_id"], :name => "Category Data ID"
  add_index "sfcatdata", ["category_node_id"], :name => "Category Node ID"
  add_index "sfcatdata", ["created_by_id"], :name => "Created By ID"
  add_index "sfcatdata", ["last_modified_by_id"], :name => "Last Modified By ID"
  add_index "sfcatdata", ["s_object_id"], :name => "SObject ID"
  add_index "sfcatdata", ["category_node_id"], :name => "index_sfcatdata_on_category_node_id"
  add_index "sfcatdata", ["related_sobject_id"], :name => "index_sfcatdata_on_related_sobject_id"

  create_table "sfcatnode", :force => true do |t|
    t.string   "sf_id"
    t.string   "name"
    t.string   "subcategory_sort_style"
    t.string   "parent_category_node_id"
    t.float    "sort_order"
    t.string   "created_by_id"
    t.datetime "created_date"
    t.string   "last_modified_by_id"
    t.datetime "last_modified_date"
    t.datetime "system_modstamp"
    t.string   "parent_id"
    t.string   "master_label"
    t.string   "sort_style"
  end

  add_index "sfcatnode", ["sf_id"], :name => "sfcatnode_sf_id_idx", :unique => true
  add_index "sfcatnode", ["sf_id"], :name => "Category Node ID"
  add_index "sfcatnode", ["created_by_id"], :name => "Created By ID"
  add_index "sfcatnode", ["last_modified_by_id"], :name => "Last Modified By ID"
  add_index "sfcatnode", ["parent_category_node_id"], :name => "Parent Category Node ID"
  add_index "sfcatnode", ["sf_id"], :name => "index_sfcatnode_on_sf_id"
  add_index "sfcatnode", ["parent_id"], :name => "index_sfcatnode_on_parent_id"

  create_table "sfccomment", :force => true do |t|
    t.string   "parent_id"
    t.string   "is_published"
    t.text     "comment_body"
    t.string   "created_by_id"
    t.datetime "created_date"
    t.datetime "system_modstamp"
    t.string   "sf_id",               :default => "", :null => false
    t.string   "last_modified_date"
    t.string   "last_modified_by_id"
    t.string   "is_deleted"
  end

  add_index "sfccomment", ["sf_id"], :name => "sfccomment_sf_id_idx", :unique => true
  add_index "sfccomment", ["parent_id"], :name => "index_sfccomment_on_parent_id"

  create_table "sfcomponent", :force => true do |t|
    t.string   "sf_id"
    t.string   "owner_id"
    t.boolean  "is_deleted"
    t.string   "name"
    t.string   "currency_iso_code"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "list_address__c"
    t.string   "lookup__c"
    t.string   "list_alias__c"
    t.string   "description__c"
    t.string   "product_team_id__c"
  end

  create_table "sfcontact", :force => true do |t|
    t.string   "account_id"
    t.string   "last_name"
    t.string   "first_name"
    t.string   "salutation"
    t.string   "record_type_id"
    t.string   "other_street"
    t.string   "other_city"
    t.string   "other_state"
    t.string   "other_postal_code"
    t.string   "other_country"
    t.string   "mailing_street"
    t.string   "mailing_city"
    t.string   "mailing_state"
    t.string   "mailing_postal_code"
    t.string   "mailing_country"
    t.string   "phone"
    t.string   "fax"
    t.string   "mobile_phone"
    t.string   "home_phone"
    t.string   "other_phone"
    t.string   "assistant_phone"
    t.string   "reports_to_id"
    t.string   "email"
    t.string   "title"
    t.string   "department"
    t.string   "assistant_name"
    t.string   "lead_source"
    t.date     "birthdate"
    t.text     "description"
    t.string   "owner_id"
    t.string   "has_opted_out_of_email"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.datetime "last_cu_request_date"
    t.datetime "last_cu_update_date"
    t.string   "portal_password__c"
    t.string   "magma_user__c"
    t.string   "contact_status__c"
    t.string   "personal_invite_only__c"
    t.string   "product_group__c"
    t.string   "notification_frequency__c"
    t.string   "mail_stop__c"
    t.string   "contact_user_id__c"
    t.string   "frequency__c"
    t.datetime "last_report__c"
    t.string   "business_unit__c"
    t.datetime "notification_last_sent__c"
    t.string   "dont_send_empty_report__c"
    t.string   "list_alias__c"
    t.date     "start_date__c"
    t.date     "orientation_date__c"
    t.string   "laptop__c"
    t.string   "linux_workstation__c"
    t.string   "sun_workstation__c"
    t.string   "special_requests_admin__c"
    t.string   "dept__c"
    t.string   "special_requests_it__c"
    t.string   "employee_number__c"
    t.string   "users_without_emp_num__c"
    t.string   "contacts_without_emp_num__c"
    t.datetime "portal_last_login_date__c"
    t.string   "portal_login_count__c"
    t.date     "portal_last_login_date_fmt__c"
    t.string   "local_name__c"
    t.string   "portal_username__c"
    t.string   "reassign_to_user_id__c"
    t.string   "branches_approved_by_user_id__c"
    t.string   "branches_approved_by__c"
    t.string   "reassign_to__c"
    t.string   "pr_cr_detail_level__c"
    t.string   "pr_frequency__c"
    t.datetime "pr_last_report_date_time__c"
    t.string   "pr_no_empty__c"
    t.string   "pr_branch_detail_level__c"
    t.string   "local_title__c"
    t.string   "localized_dept__c"
    t.string   "localized_business_unit__c"
    t.datetime "portal_last_login_fail_date__c"
    t.string   "portal_login_fail_count__c"
    t.string   "tags__c"
    t.float    "portal_login_success__c"
    t.string   "portal_total_login_seconds__c"
    t.string   "portal_max_login_seconds__c"
    t.string   "portal_average_login_seconds__c"
    t.date     "order_download_until__c"
    t.string   "order_rtu_id__c"
    t.string   "hr_survey__c"
    t.string   "license_delivery_contact__c"
    t.string   "full_name__c"
    t.string   "last_login_failed__c"
    t.string   "sf_id",                            :default => "", :null => false
    t.string   "portal_privilege__c"
    t.datetime "portal_last_confirm_date__c"
    t.datetime "portal_last_confirm_sent_date__c"
    t.string   "user_id__c"
    t.string   "welcome_email_sent_at__c"
    t.string   "password_reset_sent_at__c"
    t.string   "portal_last_version__c"
    t.string   "portal_server__c"
    t.string   "email_flyer__c"
    t.string   "name"
    t.string   "last_activity_date"
    t.string   "currency_iso_code"
    t.string   "is_deleted"
    t.string   "master_record_id"
  end

  add_index "sfcontact", ["sf_id"], :name => "sfcontact_sf_id_idx", :unique => true
  add_index "sfcontact", ["sf_id"], :name => "index_sfcontact_on_sf_id"

  create_table "sfcontact_setting", :force => true do |t|
    t.string "sfcontact_id"
    t.string "token"
  end

  add_index "sfcontact_setting", ["sfcontact_id"], :name => "index_sfcontact_setting_on_sfcontact_id"

  create_table "sfgroup", :force => true do |t|
    t.string   "sf_id"
    t.string   "name"
    t.string   "related_id"
    t.string   "type"
    t.string   "email"
    t.string   "owner_id"
    t.boolean  "does_send_email_to_members"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "sf_type"
  end

  create_table "sfmolten_post", :force => true do |t|
    t.string   "sf_id"
    t.string   "owner_id"
    t.string   "name"
    t.string   "record_type_id"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.text     "body__c"
    t.string   "page__c"
    t.string   "currency_iso_code"
    t.string   "valid_from__c"
    t.string   "valid_to__c"
    t.string   "is_deleted"
    t.string   "title_long__c"
  end

  create_table "sfproduct_team", :force => true do |t|
    t.string   "sf_id"
    t.string   "owner_id"
    t.boolean  "is_deleted"
    t.string   "name"
    t.string   "currency_iso_code"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "description__c"
    t.string   "lookup__c"
    t.string   "build_account__c"
    t.string   "business_unit__c"
    t.string   "products__c"
    t.string   "bu_description__c"
    t.string   "team_alias__c"
    t.string   "build_account_contact_id__c"
  end

  create_table "sfsolution", :force => true do |t|
    t.integer  "solution_number",                 :limit => 10
    t.string   "solution_name"
    t.string   "is_published"
    t.string   "is_published_in_public_kb"
    t.string   "status"
    t.string   "record_type_id"
    t.string   "is_reviewed"
    t.text     "solution_note"
    t.string   "owner_id"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.string   "solution_type__c"
    t.string   "account_specific__c"
    t.string   "account_name__c"
    t.string   "publish_request__c"
    t.string   "initial_version__c"
    t.string   "final_version__c"
    t.string   "special_build__c"
    t.date     "effective_date__c"
    t.string   "product_name__c"
    t.string   "component__c"
    t.string   "sme_reviewer_id__c"
    t.string   "sub_status__c"
    t.string   "question_problem__c"
    t.string   "answer_workaround__c"
    t.string   "error_warning_message__c"
    t.string   "message_description__c"
    t.string   "solution_workaround__c"
    t.string   "solution_answer__c"
    t.string   "enter_solution_error_message__c"
    t.string   "test_solution__c"
    t.string   "test_error__c"
    t.string   "sf_id",                                         :default => "", :null => false
    t.string   "approve__c"
    t.string   "reject__c"
    t.string   "region__c"
    t.string   "times_used"
    t.string   "currency_iso_code"
    t.string   "published_date__c"
    t.string   "is_deleted"
    t.string   "portal_account_name_id__c"
    t.string   "publish_approved__c"
    t.string   "is_html"
  end

  add_index "sfsolution", ["sf_id"], :name => "sfsolution_sf_id_idx", :unique => true
  add_index "sfsolution", ["sf_id"], :name => "index_sfsolution_on_sf_id"

  create_table "sfsolution_setting", :force => true do |t|
    t.string  "sfsolution_id"
    t.integer "views",         :default => 0
    t.integer "relevancy",     :default => 50
    t.integer "updates",       :default => 0
  end

  create_table "sfssl", :force => true do |t|
    t.string   "last_name"
    t.string   "first_name"
    t.string   "username"
    t.string   "email"
    t.string   "is_active"
    t.string   "time_zone_sid_key"
    t.string   "locale_sid_key"
    t.string   "contact_id"
    t.string   "language_locale_key"
    t.string   "super_user"
    t.datetime "last_login_date"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.string   "sf_id",               :default => "", :null => false
    t.string   "system_modstamp"
    t.string   "name"
  end

  add_index "sfssl", ["sf_id"], :name => "sfssl_sf_id_idx", :unique => true

  create_table "sfuser", :force => true do |t|
    t.string   "username"
    t.string   "last_name"
    t.string   "first_name"
    t.string   "company_name"
    t.string   "division"
    t.string   "department"
    t.string   "title"
    t.string   "street"
    t.string   "city"
    t.string   "state"
    t.string   "postal_code"
    t.string   "country"
    t.string   "email"
    t.string   "phone"
    t.string   "fax"
    t.string   "mobile_phone"
    t.string   "alias"
    t.string   "is_active"
    t.string   "time_zone_sid_key"
    t.string   "user_role_id"
    t.string   "locale_sid_key"
    t.string   "receives_info_emails"
    t.string   "receives_admin_info_emails"
    t.string   "email_encoding_key"
    t.string   "profile_id"
    t.string   "language_locale_key"
    t.string   "employee_number"
    t.datetime "last_login_date"
    t.datetime "created_date"
    t.string   "created_by_id"
    t.datetime "last_modified_date"
    t.string   "last_modified_by_id"
    t.datetime "system_modstamp"
    t.datetime "offline_trial_expiration_date"
    t.datetime "offline_pda_trial_expiration_date"
    t.string   "user_permissions_marketing_user"
    t.string   "user_permissions_offline_user"
    t.string   "user_permissions_avantgo_user"
    t.string   "forecast_enabled"
    t.string   "reports_to__c"
    t.string   "lookup_user__c"
    t.string   "ex_employee__c"
    t.string   "user_contact_id__c",                                :default => "", :null => false
    t.string   "description__c",                                    :default => "", :null => false
    t.string   "sf_id",                                             :default => "", :null => false
    t.string   "name"
    t.string   "default_currency_iso_code"
    t.string   "currency_iso_code"
    t.string   "next_automated_approver_id__c"
    t.string   "expense_approving_manager_id__c"
    t.string   "profile_license_type"
    t.string   "delegated_approver_id"
    t.string   "user_permissions_mobile_user"
    t.string   "user_preferences_activity_reminders_popup"
    t.string   "user_preferences_event_reminders_checkbox_default"
    t.string   "user_preferences_task_reminders_checkbox_default"
    t.string   "user_preferences_reminder_sound_off"
    t.string   "extension"
    t.string   "full_name__c"
    t.string   "user_permissions_call_center_auto_login"
    t.string   "call_center_id"
    t.string   "contact_id"
    t.string   "user_type"
    t.string   "manager_id"
  end

  add_index "sfuser", ["sf_id"], :name => "sfuser_sf_id_idx", :unique => true
  add_index "sfuser", ["sf_id"], :name => "index_sfuser_on_sf_id"

  create_table "solution_relevancy", :force => true do |t|
    t.integer "rating_value_one"
    t.integer "rating_value_two"
    t.integer "rating_value_three"
    t.integer "rating_value_four"
    t.integer "view_value"
    t.integer "update_value"
  end

  create_table "solution_search_log", :force => true do |t|
    t.integer  "contact_id"
    t.string   "term"
    t.integer  "results_count"
    t.datetime "created_at"
  end

  create_table "tip", :force => true do |t|
    t.string   "title"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "page_id"
  end

  create_table "viewing", :force => true do |t|
    t.string   "viewable_id"
    t.string   "viewable_type"
    t.string   "sfcontact_id"
    t.datetime "created_at"
  end

  add_index "viewing", ["sfcontact_id"], :name => "index_viewing_on_sfcontact_id"
  add_index "viewing", ["viewable_type"], :name => "index_viewing_on_viewable_type"

end
