## Local MySQL Database ##
### THESE DATABASE NAMES MUST STAY THE SAME

login: &login
  adapter: mysql
  host: localhost
  username: root
  password: peekaboo

development:
  database: molten_development
  <<: *login

test:
  database: molten_test
  <<: *login

production:
  database: molten_development
  <<: *login

## SalesForce ##

salesforce:
  adapter: activesalesforce
  url: https://www.salesforce.com/services/Soap/u/7.0
  username: molten_admin@magma-da.com
  password: u2cansleeprWI2X9JakDlxjcuAofhggFbaf