CREATE TABLE `app_setting` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `value` varchar(255) default NULL,
  `description` text,
  `updated_at` datetime default NULL,
  `field_type` varchar(255) default 'text_field',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

CREATE TABLE `article` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(255) default NULL,
  `body` text,
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `case_columns_setting` (
  `id` int(11) NOT NULL auto_increment,
  `sfcontact_setting_id` int(11) default NULL,
  `your_component__c` tinyint(1) default '1',
  `your_sfuser___last_name` tinyint(1) default '1',
  `your_sf_type` tinyint(1) default '1',
  `your_customer_priority__c` tinyint(1) default '1',
  `your_sfcase___created_date` tinyint(1) default '1',
  `your_sfcase___last_updated__c` tinyint(1) default NULL,
  `your_sfcontact___last_name` tinyint(1) default '0',
  `your_expected_resolution_date__c` tinyint(1) default '0',
  `all_component__c` tinyint(1) default '1',
  `all_sfuser___last_name` tinyint(1) default '1',
  `all_sf_type` tinyint(1) default '1',
  `all_customer_priority__c` tinyint(1) default '1',
  `all_sfcase___created_date` tinyint(1) default '1',
  `all_sfcase___last_updated__c` tinyint(1) default NULL,
  `all_sfcontact___last_name` tinyint(1) default '0',
  `all_expected_resolution_date__c` tinyint(1) default '0',
  `your_cr_status__c` tinyint(1) default '0',
  `all_cr_status__c` tinyint(1) default '0',
  `your_expedited_priority__c` tinyint(1) default NULL,
  `your_contact_id` tinyint(1) default NULL,
  `your_customer_tracking__c` tinyint(1) default NULL,
  `your_weekly_notes__c` tinyint(1) default NULL,
  `all_expedited_priority__c` tinyint(1) default NULL,
  `all_contact_id` tinyint(1) default NULL,
  `all_customer_tracking__c` tinyint(1) default NULL,
  `all_weekly_notes__c` tinyint(1) default NULL,
  `your_tag__c` tinyint(1) default NULL,
  `all_tag__c` tinyint(1) default NULL,
  `your_cr_number__c` tinyint(1) default NULL,
  `all_cr_number__c` tinyint(1) default NULL,
  `your_account` tinyint(1) default NULL,
  `all_account` tinyint(1) default NULL,
  `all_expected_build_date__c` tinyint(1) default NULL,
  `your_expected_build_date__c` tinyint(1) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17197 DEFAULT CHARSET=latin1;

CREATE TABLE `case_report` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `contact_id` varchar(255) default NULL,
  `query` varchar(255) default NULL,
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  `shared` tinyint(1) default NULL,
  `columns` varchar(255) default NULL,
  `account_id` varchar(255) default NULL,
  `status_array` text,
  `column_array` text,
  `account_ids_array` text,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;

CREATE TABLE `case_view_setting` (
  `id` int(11) NOT NULL auto_increment,
  `sfcontact_setting_id` varchar(255) default NULL,
  `status` text,
  `viewable` tinyint(1) default '1',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6255 DEFAULT CHARSET=latin1;

CREATE TABLE `error` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `sf_entity` varchar(255) default NULL,
  `sql_entity` varchar(255) default NULL,
  `error_message` longtext,
  `created_time` datetime default NULL,
  `other_information` longtext,
  `last_modified` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

CREATE TABLE `page` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `controller` varchar(255) default NULL,
  `action` varchar(255) default NULL,
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `rails_cron` (
  `id` int(11) NOT NULL auto_increment,
  `command` text,
  `start` int(11) default NULL,
  `finish` int(11) default NULL,
  `every` int(11) default NULL,
  `concurrent` tinyint(1) default NULL,
  `interval_string` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

CREATE TABLE `rating` (
  `id` int(11) NOT NULL auto_increment,
  `one` int(11) default '0',
  `two` int(11) default '0',
  `three` int(11) default '0',
  `four` int(11) default '0',
  `sfsolution_id` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5834 DEFAULT CHARSET=utf8;

CREATE TABLE `refresh_cache` (
  `id` int(11) NOT NULL auto_increment,
  `refreshable_type` varchar(255) default NULL,
  `refreshable_id` varchar(255) default NULL,
  `created_at` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1274 DEFAULT CHARSET=utf8;

CREATE TABLE `schema_info` (
  `version` int(11) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `sfaccount` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `sf_type` varchar(255) default NULL,
  `parent_id` varchar(255) default NULL,
  `billing_street` varchar(255) default NULL,
  `billing_city` varchar(255) default NULL,
  `billing_state` varchar(255) default NULL,
  `billing_postal_code` varchar(255) default NULL,
  `billing_country` varchar(255) default NULL,
  `shipping_street` varchar(255) default NULL,
  `shipping_city` varchar(255) default NULL,
  `shipping_state` varchar(255) default NULL,
  `shipping_postal_code` varchar(255) default NULL,
  `shipping_country` varchar(255) default NULL,
  `phone` varchar(255) default NULL,
  `fax` varchar(255) default NULL,
  `website` varchar(255) default NULL,
  `description` longtext,
  `site` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `host_id__c` varchar(255) default NULL,
  `sales_region__c` varchar(255) default NULL,
  `dun_snumber__c` varchar(255) default NULL,
  `tam_front_end_seats__c` varchar(255) default NULL,
  `tam_back_end_seats__c` varchar(255) default NULL,
  `customer_id__c` varchar(255) default NULL,
  `address_issue__c` varchar(255) default NULL,
  `credit_rating__c` varchar(255) default NULL,
  `nda__c` varchar(255) default NULL,
  `nda_description__c` varchar(255) default NULL,
  `customer_support_alias__c` varchar(255) default NULL,
  `sap_sync_status__c` varchar(255) default NULL,
  `sap_payment_terms__c` varchar(255) default NULL,
  `sap_account_group__c` varchar(255) default NULL,
  `lead_ae_email__c` varchar(255) default NULL,
  `sap_sales_districts__c` varchar(255) default NULL,
  `sap_customer_id__c` varchar(255) default NULL,
  `tsmc_lib_nda_front_end__c` varchar(255) default NULL,
  `sap_legacy_id__c` varchar(255) default NULL,
  `sla__c` varchar(255) default NULL,
  `initial_sap_upload__c` varchar(255) default NULL,
  `nda_expiration_date__c` date default NULL,
  `tsmc_lib_nda_complete__c` varchar(255) default NULL,
  `credit_score__c` varchar(255) default NULL,
  `entity_type__c` varchar(255) default NULL,
  `credit_score_updated__c` date default NULL,
  `activities__c` longtext,
  `dns_domain__c` varchar(255) default NULL,
  `allow_molten__c` varchar(255) default NULL,
  `toll_free_phone__c` varchar(255) default NULL,
  `account_type_code__c` varchar(255) default NULL,
  `sap_org_id__c` varchar(255) default NULL,
  `sf_id` varchar(255) NOT NULL default '',
  `type` varchar(255) default NULL,
  `sap_log_id__c` varchar(255) default NULL,
  `vat__c` varchar(255) default NULL,
  `sap_shipping_account_id__c` varchar(255) default NULL,
  `email_flyer__c` varchar(255) default NULL,
  `last_activity_date` varchar(255) default NULL,
  `sap_customer_tax_group__c` varchar(255) default NULL,
  `portal_default_type__c` varchar(255) default NULL,
  `portal_case_types__c` varchar(255) default NULL,
  `portal_case_scope__c` varchar(255) default NULL,
  `industry` varchar(255) default NULL,
  `annual_revenue` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  `master_record_id` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfaccount_sf_id_idx` (`sf_id`),
  KEY `index_sfaccount_on_sf_id` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3236 DEFAULT CHARSET=latin1;

CREATE TABLE `sfattach` (
  `id` int(11) NOT NULL auto_increment,
  `parent_id` varchar(255) character set latin1 default NULL,
  `name` varchar(255) character set latin1 default NULL,
  `is_private` varchar(255) character set latin1 default NULL,
  `content_type` varchar(255) character set latin1 default NULL,
  `body_length` int(11) default NULL,
  `body` longtext character set latin1,
  `owner_id` varchar(255) character set latin1 default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) character set latin1 default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) character set latin1 default NULL,
  `system_modstamp` datetime default NULL,
  `sf_id` varchar(255) character set latin1 NOT NULL default '',
  `is_deleted` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfattach_sf_id_idx` (`sf_id`),
  KEY `index_sfattach_on_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27264 DEFAULT CHARSET=utf8;

CREATE TABLE `sfcase` (
  `id` int(11) NOT NULL auto_increment,
  `case_number` int(11) default NULL,
  `contact_id` varchar(255) default NULL,
  `asset_id` varchar(255) default NULL,
  `supplied_name` varchar(255) default NULL,
  `supplied_email` varchar(255) default NULL,
  `supplied_phone` varchar(255) default NULL,
  `supplied_company` varchar(255) default NULL,
  `sf_type` varchar(255) default NULL,
  `record_type_id` varchar(255) default NULL,
  `status` varchar(255) default NULL,
  `origin` varchar(255) default NULL,
  `is_visible_in_self_service` varchar(255) default NULL,
  `subject` varchar(255) default NULL,
  `priority` varchar(255) default NULL,
  `description` longtext,
  `is_closed` varchar(255) default NULL,
  `closed_date` datetime default NULL,
  `is_escalated` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `quart_formal__c` varchar(255) default NULL,
  `clarify_id__c` varchar(255) default NULL,
  `originator__c` varchar(255) default NULL,
  `customer_priority__c` varchar(255) default NULL,
  `operating_system__c` varchar(255) default NULL,
  `reproducible__c` varchar(255) default NULL,
  `component__c` varchar(255) default NULL,
  `customer_tracking__c` varchar(255) default NULL,
  `query_build_view__c` varchar(255) default NULL,
  `dataor_test_case_provided__c` varchar(255) default NULL,
  `design_geometryn_m__c` varchar(255) default NULL,
  `foundry__c` varchar(255) default NULL,
  `cell_count_k_objects__c` varchar(255) default NULL,
  `speed_m_hz__c` varchar(255) default NULL,
  `scopeof_flow__c` varchar(255) default NULL,
  `formal_verification__c` varchar(255) default NULL,
  `qualityof_results__c` varchar(255) default NULL,
  `hdl__c` varchar(255) default NULL,
  `test_case_path__c` varchar(255) default NULL,
  `std_cell_library__c` varchar(255) default NULL,
  `tape_out_date__c` date default NULL,
  `synthesis_tool__c` varchar(255) default NULL,
  `schedule_status__c` varchar(255) default NULL,
  `time_stamp_build__c` varchar(255) default NULL,
  `version_number__c` varchar(255) default NULL,
  `noise_signoff__c` varchar(255) default NULL,
  `power_signoff__c` varchar(255) default NULL,
  `clarify_customer__c` varchar(255) default NULL,
  `analysis_tool__c` varchar(255) default NULL,
  `target_release__c` varchar(255) default NULL,
  `clarify_create_date__c` date default NULL,
  `program_area__c` varchar(255) default NULL,
  `expedited_priority__c` varchar(255) default NULL,
  `target_fast_track_build__c` date default NULL,
  `estimated_start_date__c` date default NULL,
  `estimated_finish_date__c` date default NULL,
  `test_case_provided__c` varchar(255) default NULL,
  `customer_visible__c` varchar(255) default NULL,
  `opportunity_name__c` varchar(255) default NULL,
  `requested_start_date__c` date default NULL,
  `requested_end_date__c` date default NULL,
  `initial_quality_of_results__c` varchar(255) default NULL,
  `initial_util__c` float default NULL,
  `palace_options_used__c` varchar(255) default NULL,
  `initial_speed__c` varchar(255) default NULL,
  `design_top_level_name__c` varchar(255) default NULL,
  `mode__c` varchar(255) default NULL,
  `number_of_clocks__c` varchar(255) default NULL,
  `number_of_design_blocks__c` varchar(255) default NULL,
  `power_analysis_tool__c` varchar(255) default NULL,
  `tape_out_limiting__c` varchar(255) default NULL,
  `sales_opportunity_related__c` varchar(255) default NULL,
  `benmark_impacted__c` varchar(255) default NULL,
  `special_situation__c` varchar(255) default NULL,
  `special_situation_desc__c` varchar(255) default NULL,
  `benchmark_case__c` varchar(255) default NULL,
  `product__c` varchar(255) default NULL,
  `is_closeable__c` varchar(255) default NULL,
  `schedule_comments__c` varchar(255) default NULL,
  `shadow_status__c` varchar(255) default NULL,
  `code_streams_priority__c` varchar(255) default NULL,
  `tag__c` varchar(255) default NULL,
  `engineer_assigned__c` varchar(255) default NULL,
  `logic_verification__c` varchar(255) default NULL,
  `physical_verification__c` varchar(255) default NULL,
  `extraction__c` varchar(255) default NULL,
  `timing_signoff__c` varchar(255) default NULL,
  `dft__c` varchar(255) default NULL,
  `expected_build_date__c` date default NULL,
  `man_hours_of_effort__c` varchar(255) default NULL,
  `workaround_description__c` varchar(255) default NULL,
  `workaround_available__c` varchar(255) default NULL,
  `needs_docs__c` varchar(255) default NULL,
  `target_releases__c` varchar(255) default NULL,
  `expected_resolution_date__c` date default NULL,
  `fix_version__c` varchar(255) default NULL,
  `cr_list_id__c` varchar(255) default NULL,
  `crash_details__c` varchar(255) default NULL,
  `description_notes__c` varchar(255) default NULL,
  `tech_campaign_id__c` varchar(255) default NULL,
  `release_note__c` varchar(255) default NULL,
  `tech_campaign2_id__c` varchar(255) default NULL,
  `r_d_submission__c` varchar(255) default NULL,
  `pe_owner_user_id__c` varchar(255) default NULL,
  `component_link_id__c` varchar(255) default NULL,
  `aging_weeks__c` varchar(255) default NULL,
  `internal_comments__c` varchar(255) default NULL,
  `committed__c` varchar(255) default NULL,
  `level_of_effort__c` float default NULL,
  `sf_id` varchar(255) NOT NULL default '',
  `type` varchar(255) default NULL,
  `sql_sync_id__c` varchar(255) default NULL,
  `pe_checkpoint_id__c` varchar(255) default NULL,
  `status_1_stream__c` varchar(255) default NULL,
  `status_2_stream__c` varchar(255) default NULL,
  `status_3_stream__c` varchar(255) default NULL,
  `x1st_stream__c` varchar(255) default NULL,
  `x2nd_stream__c` varchar(255) default NULL,
  `x3rd_stream__c` varchar(255) default NULL,
  `weekly_notes__c` varchar(255) default NULL,
  `tech_campaign_task_id__c` varchar(255) default NULL,
  `due_date__c` varchar(255) default NULL,
  `has_comments_unread_by_owner` varchar(255) default NULL,
  `has_css_comments` varchar(255) default NULL,
  `fast_track_required__c` varchar(255) default NULL,
  `target_analysis_done__c` varchar(255) default NULL,
  `target_fix_available__c` varchar(255) default NULL,
  `target_fix_merged__c` varchar(255) default NULL,
  `actual_analysis_done__c` varchar(255) default NULL,
  `actual_fix_available__c` varchar(255) default NULL,
  `actual_fix_merged__c` varchar(255) default NULL,
  `actual_fix_to_scm__c` varchar(255) default NULL,
  `target_fix_stream__c` varchar(255) default NULL,
  `cr_status__c` varchar(255) default NULL,
  `customer_account_id__c` varchar(255) default NULL,
  `related_documentation_completed__c` varchar(255) default NULL,
  `reason_for_urgent_and_critical_priority__c` varchar(255) default NULL,
  `committed_finish_date__c` varchar(255) default NULL,
  `delta_commit_to_actual__c` varchar(255) default NULL,
  `committed_fix_date__c` varchar(255) default NULL,
  `delta_expected_to_commit__c` varchar(255) default NULL,
  `r_d_first_owner__c` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `first_support_owner__c` varchar(255) default NULL,
  `reason` varchar(255) default NULL,
  `account_id` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  `has_self_service_comments` varchar(255) default NULL,
  `parent_id` varchar(255) default NULL,
  `r_d_owner_id__c` varchar(255) default NULL,
  `branch_name__c` varchar(255) default NULL,
  `estimated_effort__c` varchar(255) default NULL,
  `internal_release_number__c` varchar(255) default NULL,
  `external_release_number__c` varchar(255) default NULL,
  `other__c` varchar(255) default NULL,
  `fixed_version__c` varchar(255) default NULL,
  `last_updated__c` datetime default NULL,
  `critical_date__c` varchar(255) default NULL,
  `latest_scm_or_ft_build_tested_against__c` varchar(255) default NULL,
  `last_modified_age__c` varchar(255) default NULL,
  `task_force__c` varchar(255) default NULL,
  `cr_number__c` varchar(255) default NULL,
  `parent_case_id__c` varchar(255) default NULL,
  `release_notes_documentation__c` varchar(255) default NULL,
  `unit_system_test_details__c` varchar(255) default NULL,
  `tech_pubs_completed__c` varchar(255) default NULL,
  `cc__c` varchar(255) default NULL,
  `marketing_input__c` varchar(255) default NULL,
  `tf_status__c` varchar(255) default NULL,
  `tf_resolved__c` varchar(255) default NULL,
  `tf_grouping_text__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sf_id_idx` (`sf_id`),
  KEY `index_sfcase_on_contact_id` (`contact_id`),
  KEY `index_sfcase_on_sf_id` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=72211 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcase_watcher` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `is_deleted` tinyint(1) default NULL,
  `name` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `last_activity_date` date default NULL,
  `case_number_id__c` varchar(255) default NULL,
  `case_fields_deferred__c` varchar(255) default NULL,
  `tech_campaign_id__c` varchar(255) default NULL,
  `user_id__c` varchar(255) default NULL,
  `account_id__c` varchar(255) default NULL,
  `case_fields__c` varchar(255) default NULL,
  `case_scope__c` varchar(255) default NULL,
  `component_id__c` varchar(255) default NULL,
  `team_id__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=500 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcase_watcher_list` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `is_deleted` tinyint(1) default NULL,
  `name` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `last_activity_date` date default NULL,
  `contact_id__c` varchar(255) default NULL,
  `alias_email__c` varchar(255) default NULL,
  `case_watcher_id__c` varchar(255) default NULL,
  `email__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=817 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcatdata` (
  `id` int(18) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `category_node_id` varchar(255) default NULL,
  `s_object_id` varchar(255) default NULL,
  `created_by_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `system_modstamp` datetime default NULL,
  `related_sobject_id` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfcatdata_sf_id_idx` (`sf_id`),
  KEY `Category Data ID` (`sf_id`),
  KEY `Category Node ID` (`category_node_id`),
  KEY `Created By ID` (`created_by_id`),
  KEY `Last Modified By ID` (`last_modified_by_id`),
  KEY `SObject ID` (`s_object_id`),
  KEY `index_sfcatdata_on_category_node_id` (`category_node_id`),
  KEY `index_sfcatdata_on_related_sobject_id` (`related_sobject_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7206 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcatnode` (
  `id` int(18) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `name` varchar(255) default NULL,
  `subcategory_sort_style` varchar(255) default NULL,
  `parent_category_node_id` varchar(255) default NULL,
  `sort_order` double default NULL,
  `created_by_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `system_modstamp` datetime default NULL,
  `parent_id` varchar(255) default NULL,
  `master_label` varchar(255) default NULL,
  `sort_style` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfcatnode_sf_id_idx` (`sf_id`),
  KEY `Category Node ID` (`sf_id`),
  KEY `Created By ID` (`created_by_id`),
  KEY `Last Modified By ID` (`last_modified_by_id`),
  KEY `Parent Category Node ID` (`parent_category_node_id`),
  KEY `index_sfcatnode_on_sf_id` (`sf_id`),
  KEY `index_sfcatnode_on_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=latin1;

CREATE TABLE `sfccomment` (
  `id` int(11) NOT NULL auto_increment,
  `parent_id` varchar(255) default NULL,
  `is_published` varchar(255) default NULL,
  `comment_body` longtext,
  `created_by_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `system_modstamp` datetime default NULL,
  `sf_id` varchar(255) NOT NULL default '',
  `last_modified_date` varchar(255) default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfccomment_sf_id_idx` (`sf_id`),
  KEY `index_sfccomment_on_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=151445 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcomponent` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `is_deleted` tinyint(1) default NULL,
  `name` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `list_address__c` varchar(255) default NULL,
  `lookup__c` varchar(255) default NULL,
  `list_alias__c` varchar(255) default NULL,
  `description__c` varchar(255) default NULL,
  `product_team_id__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

CREATE TABLE `sfcontact` (
  `id` int(11) NOT NULL auto_increment,
  `account_id` varchar(255) character set latin1 default NULL,
  `last_name` varchar(255) character set latin1 default NULL,
  `first_name` varchar(255) character set latin1 default NULL,
  `salutation` varchar(255) character set latin1 default NULL,
  `record_type_id` varchar(255) character set latin1 default NULL,
  `other_street` varchar(255) character set latin1 default NULL,
  `other_city` varchar(255) character set latin1 default NULL,
  `other_state` varchar(255) character set latin1 default NULL,
  `other_postal_code` varchar(255) character set latin1 default NULL,
  `other_country` varchar(255) character set latin1 default NULL,
  `mailing_street` varchar(255) character set latin1 default NULL,
  `mailing_city` varchar(255) character set latin1 default NULL,
  `mailing_state` varchar(255) character set latin1 default NULL,
  `mailing_postal_code` varchar(255) character set latin1 default NULL,
  `mailing_country` varchar(255) character set latin1 default NULL,
  `phone` varchar(255) character set latin1 default NULL,
  `fax` varchar(255) character set latin1 default NULL,
  `mobile_phone` varchar(255) character set latin1 default NULL,
  `home_phone` varchar(255) character set latin1 default NULL,
  `other_phone` varchar(255) character set latin1 default NULL,
  `assistant_phone` varchar(255) character set latin1 default NULL,
  `reports_to_id` varchar(255) character set latin1 default NULL,
  `email` varchar(255) character set latin1 default NULL,
  `title` varchar(255) character set latin1 default NULL,
  `department` varchar(255) character set latin1 default NULL,
  `assistant_name` varchar(255) character set latin1 default NULL,
  `lead_source` varchar(255) character set latin1 default NULL,
  `birthdate` date default NULL,
  `description` longtext character set latin1,
  `owner_id` varchar(255) character set latin1 default NULL,
  `has_opted_out_of_email` varchar(255) character set latin1 default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) character set latin1 default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) character set latin1 default NULL,
  `system_modstamp` datetime default NULL,
  `last_cu_request_date` datetime default NULL,
  `last_cu_update_date` datetime default NULL,
  `portal_password__c` varchar(255) character set latin1 default NULL,
  `magma_user__c` varchar(255) character set latin1 default NULL,
  `contact_status__c` varchar(255) character set latin1 default NULL,
  `personal_invite_only__c` varchar(255) character set latin1 default NULL,
  `product_group__c` varchar(255) character set latin1 default NULL,
  `notification_frequency__c` varchar(255) character set latin1 default NULL,
  `mail_stop__c` varchar(255) character set latin1 default NULL,
  `contact_user_id__c` varchar(255) character set latin1 default NULL,
  `frequency__c` varchar(255) character set latin1 default NULL,
  `last_report__c` datetime default NULL,
  `business_unit__c` varchar(255) character set latin1 default NULL,
  `notification_last_sent__c` datetime default NULL,
  `dont_send_empty_report__c` varchar(255) character set latin1 default NULL,
  `list_alias__c` varchar(255) character set latin1 default NULL,
  `start_date__c` date default NULL,
  `orientation_date__c` date default NULL,
  `laptop__c` varchar(255) character set latin1 default NULL,
  `linux_workstation__c` varchar(255) character set latin1 default NULL,
  `sun_workstation__c` varchar(255) character set latin1 default NULL,
  `special_requests_admin__c` varchar(255) character set latin1 default NULL,
  `dept__c` varchar(255) character set latin1 default NULL,
  `special_requests_it__c` varchar(255) character set latin1 default NULL,
  `employee_number__c` varchar(255) character set latin1 default NULL,
  `users_without_emp_num__c` varchar(255) character set latin1 default NULL,
  `contacts_without_emp_num__c` varchar(255) character set latin1 default NULL,
  `portal_last_login_date__c` datetime default NULL,
  `portal_login_count__c` varchar(255) character set latin1 default NULL,
  `portal_last_login_date_fmt__c` date default NULL,
  `local_name__c` varchar(255) character set latin1 default NULL,
  `portal_username__c` varchar(255) character set latin1 default NULL,
  `reassign_to_user_id__c` varchar(255) character set latin1 default NULL,
  `branches_approved_by_user_id__c` varchar(255) character set latin1 default NULL,
  `branches_approved_by__c` varchar(255) character set latin1 default NULL,
  `reassign_to__c` varchar(255) character set latin1 default NULL,
  `pr_cr_detail_level__c` varchar(255) character set latin1 default NULL,
  `pr_frequency__c` varchar(255) character set latin1 default NULL,
  `pr_last_report_date_time__c` datetime default NULL,
  `pr_no_empty__c` varchar(255) character set latin1 default NULL,
  `pr_branch_detail_level__c` varchar(255) character set latin1 default NULL,
  `local_title__c` varchar(255) character set latin1 default NULL,
  `localized_dept__c` varchar(255) character set latin1 default NULL,
  `localized_business_unit__c` varchar(255) character set latin1 default NULL,
  `portal_last_login_fail_date__c` datetime default NULL,
  `portal_login_fail_count__c` varchar(255) character set latin1 default NULL,
  `tags__c` varchar(255) character set latin1 default NULL,
  `portal_login_success__c` float default NULL,
  `portal_total_login_seconds__c` varchar(255) character set latin1 default NULL,
  `portal_max_login_seconds__c` varchar(255) character set latin1 default NULL,
  `portal_average_login_seconds__c` varchar(255) character set latin1 default NULL,
  `order_download_until__c` date default NULL,
  `order_rtu_id__c` varchar(255) character set latin1 default NULL,
  `hr_survey__c` varchar(255) character set latin1 default NULL,
  `license_delivery_contact__c` varchar(255) character set latin1 default NULL,
  `full_name__c` varchar(255) character set latin1 default NULL,
  `last_login_failed__c` varchar(255) character set latin1 default NULL,
  `sf_id` varchar(255) character set latin1 NOT NULL default '',
  `portal_privilege__c` varchar(255) default NULL,
  `portal_last_confirm_date__c` datetime default NULL,
  `portal_last_confirm_sent_date__c` datetime default NULL,
  `user_id__c` varchar(255) default NULL,
  `welcome_email_sent_at__c` varchar(255) default NULL,
  `password_reset_sent_at__c` varchar(255) default NULL,
  `portal_last_version__c` varchar(255) default NULL,
  `portal_server__c` varchar(255) default NULL,
  `email_flyer__c` varchar(255) default NULL,
  `name` varchar(255) default NULL,
  `last_activity_date` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  `master_record_id` varchar(255) default NULL,
  `last_read_marketing_message_id` varchar(255) default NULL,
  `account_filter_ids_array` text,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfcontact_sf_id_idx` (`sf_id`),
  KEY `index_sfcontact_on_sf_id` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21515 DEFAULT CHARSET=utf8;

CREATE TABLE `sfcontact_setting` (
  `id` int(11) NOT NULL auto_increment,
  `sfcontact_id` varchar(255) default NULL,
  `token` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  KEY `index_sfcontact_setting_on_sfcontact_id` (`sfcontact_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17197 DEFAULT CHARSET=latin1;

CREATE TABLE `sfgroup` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `name` varchar(255) default NULL,
  `related_id` varchar(255) default NULL,
  `type` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `does_send_email_to_members` tinyint(1) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `sf_type` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=323 DEFAULT CHARSET=latin1;

CREATE TABLE `sfmolten_post` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `name` varchar(255) default NULL,
  `record_type_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `body__c` text,
  `page__c` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `valid_from__c` varchar(255) default NULL,
  `valid_to__c` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  `title_long__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;

CREATE TABLE `sfproduct_team` (
  `id` int(11) NOT NULL auto_increment,
  `sf_id` varchar(255) default NULL,
  `owner_id` varchar(255) default NULL,
  `is_deleted` tinyint(1) default NULL,
  `name` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `description__c` varchar(255) default NULL,
  `lookup__c` varchar(255) default NULL,
  `build_account__c` varchar(255) default NULL,
  `business_unit__c` varchar(255) default NULL,
  `products__c` varchar(255) default NULL,
  `bu_description__c` varchar(255) default NULL,
  `team_alias__c` varchar(255) default NULL,
  `build_account_contact_id__c` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `sfsolution` (
  `id` int(11) NOT NULL auto_increment,
  `solution_number` int(10) unsigned default NULL,
  `solution_name` varchar(255) default NULL,
  `is_published` varchar(255) default NULL,
  `is_published_in_public_kb` varchar(255) default NULL,
  `status` varchar(255) default NULL,
  `record_type_id` varchar(255) default NULL,
  `is_reviewed` varchar(255) default NULL,
  `solution_note` longtext,
  `owner_id` varchar(255) default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `solution_type__c` varchar(255) default NULL,
  `account_specific__c` varchar(255) default NULL,
  `account_name__c` varchar(255) default NULL,
  `publish_request__c` varchar(255) default NULL,
  `initial_version__c` varchar(255) default NULL,
  `final_version__c` varchar(255) default NULL,
  `special_build__c` varchar(255) default NULL,
  `effective_date__c` date default NULL,
  `product_name__c` varchar(255) default NULL,
  `component__c` varchar(255) default NULL,
  `sme_reviewer_id__c` varchar(255) default NULL,
  `sub_status__c` varchar(255) default NULL,
  `question_problem__c` varchar(255) default NULL,
  `answer_workaround__c` varchar(255) default NULL,
  `error_warning_message__c` varchar(255) default NULL,
  `message_description__c` varchar(255) default NULL,
  `solution_workaround__c` varchar(255) default NULL,
  `solution_answer__c` varchar(255) default NULL,
  `enter_solution_error_message__c` varchar(255) default NULL,
  `test_solution__c` varchar(255) default NULL,
  `test_error__c` varchar(255) default NULL,
  `sf_id` varchar(255) NOT NULL default '',
  `approve__c` varchar(255) default NULL,
  `reject__c` varchar(255) default NULL,
  `region__c` varchar(255) default NULL,
  `times_used` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `published_date__c` varchar(255) default NULL,
  `is_deleted` varchar(255) default NULL,
  `portal_account_name_id__c` varchar(255) default NULL,
  `publish_approved__c` varchar(255) default NULL,
  `is_html` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfsolution_sf_id_idx` (`sf_id`),
  KEY `index_sfsolution_on_sf_id` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9717 DEFAULT CHARSET=latin1;

CREATE TABLE `sfsolution_setting` (
  `id` int(11) NOT NULL auto_increment,
  `sfsolution_id` varchar(255) default NULL,
  `views` int(11) default '0',
  `relevancy` int(11) default '50',
  `updates` int(11) default '0',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5836 DEFAULT CHARSET=latin1;

CREATE TABLE `sfssl` (
  `id` int(11) NOT NULL auto_increment,
  `last_name` varchar(255) default NULL,
  `first_name` varchar(255) default NULL,
  `username` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `is_active` varchar(255) default NULL,
  `time_zone_sid_key` varchar(255) default NULL,
  `locale_sid_key` varchar(255) default NULL,
  `contact_id` varchar(255) default NULL,
  `language_locale_key` varchar(255) default NULL,
  `super_user` varchar(255) default NULL,
  `last_login_date` datetime default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `sf_id` varchar(255) NOT NULL default '',
  `system_modstamp` varchar(255) default NULL,
  `name` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfssl_sf_id_idx` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5150 DEFAULT CHARSET=latin1;

CREATE TABLE `sfuser` (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(255) default NULL,
  `last_name` varchar(255) default NULL,
  `first_name` varchar(255) default NULL,
  `company_name` varchar(255) default NULL,
  `division` varchar(255) default NULL,
  `department` varchar(255) default NULL,
  `title` varchar(255) default NULL,
  `street` varchar(255) default NULL,
  `city` varchar(255) default NULL,
  `state` varchar(255) default NULL,
  `postal_code` varchar(255) default NULL,
  `country` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `phone` varchar(255) default NULL,
  `fax` varchar(255) default NULL,
  `mobile_phone` varchar(255) default NULL,
  `alias` varchar(255) default NULL,
  `is_active` varchar(255) default NULL,
  `time_zone_sid_key` varchar(255) default NULL,
  `user_role_id` varchar(255) default NULL,
  `locale_sid_key` varchar(255) default NULL,
  `receives_info_emails` varchar(255) default NULL,
  `receives_admin_info_emails` varchar(255) default NULL,
  `email_encoding_key` varchar(255) default NULL,
  `profile_id` varchar(255) default NULL,
  `language_locale_key` varchar(255) default NULL,
  `employee_number` varchar(255) default NULL,
  `last_login_date` datetime default NULL,
  `created_date` datetime default NULL,
  `created_by_id` varchar(255) default NULL,
  `last_modified_date` datetime default NULL,
  `last_modified_by_id` varchar(255) default NULL,
  `system_modstamp` datetime default NULL,
  `offline_trial_expiration_date` datetime default NULL,
  `offline_pda_trial_expiration_date` datetime default NULL,
  `user_permissions_marketing_user` varchar(255) default NULL,
  `user_permissions_offline_user` varchar(255) default NULL,
  `user_permissions_avantgo_user` varchar(255) default NULL,
  `forecast_enabled` varchar(255) default NULL,
  `reports_to__c` varchar(255) default NULL,
  `lookup_user__c` varchar(255) default NULL,
  `ex_employee__c` varchar(255) default NULL,
  `user_contact_id__c` varchar(255) NOT NULL default '',
  `description__c` varchar(255) NOT NULL default '',
  `sf_id` varchar(255) NOT NULL default '',
  `name` varchar(255) default NULL,
  `default_currency_iso_code` varchar(255) default NULL,
  `currency_iso_code` varchar(255) default NULL,
  `next_automated_approver_id__c` varchar(255) default NULL,
  `expense_approving_manager_id__c` varchar(255) default NULL,
  `profile_license_type` varchar(255) default NULL,
  `delegated_approver_id` varchar(255) default NULL,
  `user_permissions_mobile_user` varchar(255) default NULL,
  `user_preferences_activity_reminders_popup` varchar(255) default NULL,
  `user_preferences_event_reminders_checkbox_default` varchar(255) default NULL,
  `user_preferences_task_reminders_checkbox_default` varchar(255) default NULL,
  `user_preferences_reminder_sound_off` varchar(255) default NULL,
  `extension` varchar(255) default NULL,
  `full_name__c` varchar(255) default NULL,
  `user_permissions_call_center_auto_login` varchar(255) default NULL,
  `call_center_id` varchar(255) default NULL,
  `contact_id` varchar(255) default NULL,
  `user_type` varchar(255) default NULL,
  `manager_id` varchar(255) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `sfuser_sf_id_idx` (`sf_id`),
  KEY `index_sfuser_on_sf_id` (`sf_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1488 DEFAULT CHARSET=latin1;

CREATE TABLE `solution_relevancy` (
  `id` int(11) NOT NULL auto_increment,
  `rating_value_one` int(11) default NULL,
  `rating_value_two` int(11) default NULL,
  `rating_value_three` int(11) default NULL,
  `rating_value_four` int(11) default NULL,
  `view_value` int(11) default NULL,
  `update_value` int(11) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `solution_search_log` (
  `id` int(11) NOT NULL auto_increment,
  `contact_id` int(11) default NULL,
  `term` varchar(255) default NULL,
  `results_count` int(11) default NULL,
  `created_at` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52533 DEFAULT CHARSET=latin1;

CREATE TABLE `tip` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(255) default NULL,
  `body` text,
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  `page_id` int(11) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `viewing` (
  `id` int(11) NOT NULL auto_increment,
  `viewable_id` varchar(255) default NULL,
  `viewable_type` varchar(255) default NULL,
  `sfcontact_id` varchar(255) default NULL,
  `created_at` datetime default NULL,
  PRIMARY KEY  (`id`),
  KEY `index_viewing_on_sfcontact_id` (`sfcontact_id`),
  KEY `index_viewing_on_viewable_type` (`viewable_type`)
) ENGINE=InnoDB AUTO_INCREMENT=78895 DEFAULT CHARSET=latin1;

INSERT INTO `schema_info` (version) VALUES (73)