login: &login
  adapter: mysql
  host: localhost
  username: root
  password: peekaboo

loginP: &loginP
  adapter: mysql
  host: localhost
  username: root
  password: peekaboo

development:
  database: nearbyin_rubysite
  <<: *login

test:
  database: nearbyin_rubysite
  <<: *login

production:
  database: nearbyin_rubysite
  <<: *loginP

