# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "agg_computer_groups", :force => true do |t|
    t.column "computer_group_id", :integer,   :limit => 5,  :null => false
    t.column "total_members",     :integer,   :limit => 20, :null => false
    t.column "time_stamp",        :timestamp,               :null => false
  end

  add_index "agg_computer_groups", ["computer_group_id"], :name => "fk_reference_67"

  create_table "agg_computer_groups_benchmarks", :force => true do |t|
    t.column "agg_computer_group_id",      :integer, :limit => 20, :null => false
    t.column "benchmark_id",               :integer, :limit => 6,  :null => false
    t.column "total_applicable_computers", :integer, :limit => 20, :null => false
    t.column "total_passed_checks",        :integer, :limit => 20, :null => false
  end

  add_index "agg_computer_groups_benchmarks", ["agg_computer_group_id"], :name => "fk_reference_68"
  add_index "agg_computer_groups_benchmarks", ["benchmark_id"], :name => "fk_reference_69"

  create_table "agg_computer_groups_dlp_rule_events", :force => true do |t|
    t.column "agg_computer_group_id", :integer,   :limit => 20, :null => false
    t.column "dlp_rule_id",           :integer,   :limit => 20, :null => false
    t.column "total_instances",       :integer,   :limit => 20, :null => false
    t.column "time_stamp",            :timestamp,               :null => false
  end

  add_index "agg_computer_groups_dlp_rule_events", ["agg_computer_group_id"], :name => "fk_reference_73"
  add_index "agg_computer_groups_dlp_rule_events", ["dlp_rule_id"], :name => "fk_reference_74"

  create_table "agg_computer_groups_vulns", :force => true do |t|
    t.column "agg_computer_group_id", :integer,   :limit => 20, :null => false
    t.column "vuln_id",               :integer,   :limit => 6,  :null => false
    t.column "total_instances",       :integer,   :limit => 20, :null => false
    t.column "time_stamp",            :timestamp,               :null => false
  end

  add_index "agg_computer_groups_vulns", ["agg_computer_group_id"], :name => "fk_reference_70"
  add_index "agg_computer_groups_vulns", ["vuln_id"], :name => "fk_reference_71"

  create_table "aggregate_functions", :force => true do |t|
    t.column "name",          :string, :default => "", :null => false
    t.column "function_name", :string, :default => "", :null => false
  end

  create_table "all_computer_group_distributions", :force => true do |t|
    t.column "name",         :text,                 :default => "", :null => false
    t.column "source_table", :string, :limit => 28, :default => "", :null => false
  end

  create_table "all_properties", :force => true do |t|
    t.column "name",              :text,                  :default => "", :null => false
    t.column "report_subject_id", :integer, :limit => 20, :default => 0,  :null => false
    t.column "property_type_id",  :integer, :limit => 4,  :default => 0,  :null => false
    t.column "source_table",      :string,  :limit => 25, :default => "", :null => false
    t.column "is_aggregate",      :integer, :limit => 20, :default => 0,  :null => false
    t.column "is_default",        :integer, :limit => 4,  :default => 0,  :null => false
    t.column "is_enum",           :integer, :limit => 4,  :default => 0,  :null => false
  end

  create_table "app_relationship_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "app_relationships", :force => true do |t|
    t.column "app_id",                   :integer,              :null => false
    t.column "related_app_id",           :integer,              :null => false
    t.column "app_relationship_type_id", :integer, :limit => 3, :null => false
  end

  add_index "app_relationships", ["app_id", "related_app_id", "app_relationship_type_id"], :name => "INDEX_1"
  add_index "app_relationships", ["related_app_id"], :name => "fk_reference_20"
  add_index "app_relationships", ["app_relationship_type_id"], :name => "fk_reference_22"

  create_table "app_upgrades", :force => true do |t|
    t.column "description", :text,                 :default => "", :null => false
    t.column "from_app_id", :integer, :limit => 5,                 :null => false
    t.column "to_app_id",   :integer, :limit => 5,                 :null => false
  end

  add_index "app_upgrades", ["to_app_id"], :name => "fk_reference_40"
  add_index "app_upgrades", ["from_app_id"], :name => "fk_reference_41"

  create_table "apps", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "apps_bes", :force => true do |t|
    t.column "app_id",  :integer, :limit => 20,                  :null => false
    t.column "pattern", :string,  :limit => 512, :default => "", :null => false
  end

  add_index "apps_bes", ["app_id", "pattern"], :name => "ak_key_2", :unique => true

  create_table "apps_vulns", :id => false, :force => true do |t|
    t.column "app_id",  :integer,              :null => false
    t.column "vuln_id", :integer, :limit => 5, :null => false
  end

  add_index "apps_vulns", ["vuln_id"], :name => "fk_reference_27"

  create_table "benchmark_check_groups", :force => true do |t|
    t.column "name",                 :string,               :default => "", :null => false
    t.column "parent_id",            :integer, :limit => 5
    t.column "benchmark_version_id", :integer, :limit => 5
  end

  create_table "benchmark_check_remediations", :force => true do |t|
    t.column "benchmark_check_id",  :integer, :limit => 8, :null => false
    t.column "remediation_type_id", :integer, :limit => 3, :null => false
    t.column "description",         :text
  end

  add_index "benchmark_check_remediations", ["benchmark_check_id"], :name => "fk_reference_57"
  add_index "benchmark_check_remediations", ["remediation_type_id"], :name => "fk_reference_58"

  create_table "benchmark_check_results", :force => true do |t|
    t.column "computer_id",        :integer,   :limit => 20, :null => false
    t.column "benchmark_check_id", :integer,   :limit => 8,  :null => false
    t.column "current_state",      :string
    t.column "pass",               :boolean,                 :null => false
    t.column "valid_from",         :timestamp,               :null => false
    t.column "valid_to",           :timestamp,               :null => false
  end

  add_index "benchmark_check_results", ["computer_id", "benchmark_check_id"], :name => "INDEX_1"
  add_index "benchmark_check_results", ["benchmark_check_id"], :name => "fk_reference_35"

  create_table "benchmark_checks", :force => true do |t|
    t.column "name",                     :string,               :default => "", :null => false
    t.column "description",              :text
    t.column "desired_state",            :string
    t.column "benchmark_version_id",     :integer, :limit => 5,                 :null => false
    t.column "benchmark_check_group_id", :integer, :limit => 5
  end

  add_index "benchmark_checks", ["benchmark_version_id", "benchmark_check_group_id"], :name => "INDEX_1"
  add_index "benchmark_checks", ["benchmark_check_group_id"], :name => "fk_reference_19"

  create_table "benchmark_platforms", :id => false, :force => true do |t|
    t.column "benchmark_id", :integer, :limit => 5, :null => false
    t.column "platform_id",  :integer, :limit => 5, :null => false
  end

  create_table "benchmark_versions", :force => true do |t|
    t.column "benchmark_id", :integer,   :limit => 5, :null => false
    t.column "version",      :integer,   :limit => 3, :null => false
    t.column "publish_time", :timestamp,              :null => false
  end

  add_index "benchmark_versions", ["benchmark_id", "version"], :name => "INDEX_1"

  create_table "benchmarks", :force => true do |t|
    t.column "name",        :string, :default => "", :null => false
    t.column "description", :text
  end

  create_table "bes_sites", :force => true do |t|
    t.column "url", :string, :default => "", :null => false
  end

  add_index "bes_sites", ["url"], :name => "ak_key_2", :unique => true

  create_table "computer_apps", :force => true do |t|
    t.column "computer_id", :integer,   :limit => 20, :null => false
    t.column "app_id",      :integer,   :limit => 5,  :null => false
    t.column "port",        :integer,   :limit => 5
    t.column "valid_from",  :timestamp,               :null => false
    t.column "valid_to",    :timestamp
  end

  add_index "computer_apps", ["computer_id", "app_id"], :name => "INDEX_1"
  add_index "computer_apps", ["app_id"], :name => "fk_reference_29"

  create_table "computer_benchmark_check_remediations", :force => true do |t|
    t.column "computer_id",                    :integer,   :limit => 20, :null => false
    t.column "benchmark_check_remediation_id", :integer,   :limit => 8,  :null => false
    t.column "time_stamp",                     :timestamp,               :null => false
  end

  add_index "computer_benchmark_check_remediations", ["computer_id"], :name => "fk_reference_61"
  add_index "computer_benchmark_check_remediations", ["benchmark_check_remediation_id"], :name => "fk_reference_62"

  create_table "computer_benchmarks", :force => true do |t|
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "benchmark_id",      :integer,   :limit => 5,  :null => false
    t.column "num_checks_tested", :integer,   :limit => 5,  :null => false
    t.column "num_checks_passed", :integer,   :limit => 5,  :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp
  end

  add_index "computer_benchmarks", ["computer_id", "benchmark_id"], :name => "index_1"
  add_index "computer_benchmarks", ["benchmark_id"], :name => "fk_reference_77"

  create_table "computer_contact_relationships", :force => true do |t|
    t.column "contact_id",                    :integer, :limit => 9,                 :null => false
    t.column "relevance",                     :text,                 :default => "", :null => false
    t.column "computer_relationship_type_id", :integer, :limit => 3,                 :null => false
  end

  add_index "computer_contact_relationships", ["contact_id"], :name => "fk_reference_83"
  add_index "computer_contact_relationships", ["computer_relationship_type_id"], :name => "fk_reference_84"

  create_table "computer_group_distributions", :force => true do |t|
    t.column "name",              :string,               :default => "", :null => false
    t.column "select_clause",     :string,               :default => "", :null => false
    t.column "report_subject_id", :integer, :limit => 3,                 :null => false
  end

  create_table "computer_groups", :force => true do |t|
    t.column "name",      :string,               :default => "", :null => false
    t.column "parent_id", :integer, :limit => 5
    t.column "filter",    :text
  end

  create_table "computer_groups_computers", :force => true do |t|
    t.column "computer_group_id", :integer,   :limit => 5,  :null => false
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp
  end

  add_index "computer_groups_computers", ["computer_id"], :name => "INDEX_1"
  add_index "computer_groups_computers", ["computer_group_id"], :name => "fk_reference_51"

  create_table "computer_groups_datasource_computer_groups", :id => false, :force => true do |t|
    t.column "computer_group_id",            :integer, :limit => 6, :null => false
    t.column "datasource_computer_group_id", :integer, :limit => 6, :null => false
  end

  create_table "computer_groups_roles", :id => false, :force => true do |t|
    t.column "computer_group_id", :integer, :limit => 5, :null => false
    t.column "role_id",           :integer, :limit => 8, :null => false
  end

  add_index "computer_groups_roles", ["role_id"], :name => "fk_reference_81"

  create_table "computer_malwares", :force => true do |t|
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "malware_id",        :integer,   :limit => 20, :null => false
    t.column "malware_status_id", :integer,   :limit => 3,  :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp
  end

  add_index "computer_malwares", ["computer_id", "malware_id"], :name => "index_1"

  create_table "computer_properties", :force => true do |t|
    t.column "computer_id", :integer,   :limit => 20,                 :null => false
    t.column "property_id", :integer,   :limit => 5,                  :null => false
    t.column "value",       :string,                  :default => "", :null => false
    t.column "valid_from",  :timestamp,                               :null => false
    t.column "valid_to",    :timestamp
  end

  add_index "computer_properties", ["computer_id"], :name => "INDEX_1"
  add_index "computer_properties", ["property_id"], :name => "fk_reference_56"

  create_table "computer_relationship_type", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "computer_vuln_remediations", :force => true do |t|
    t.column "computer_id",         :integer,   :limit => 20, :null => false
    t.column "vuln_remediation_id", :integer,   :limit => 9,  :null => false
    t.column "time_stamp",          :timestamp,               :null => false
  end

  add_index "computer_vuln_remediations", ["computer_id"], :name => "fk_reference_59"
  add_index "computer_vuln_remediations", ["vuln_remediation_id"], :name => "fk_reference_60"

  create_table "computer_vulns", :force => true do |t|
    t.column "computer_id", :integer,   :limit => 20, :null => false
    t.column "vuln_id",     :integer,   :limit => 5,  :null => false
    t.column "valid_from",  :timestamp,               :null => false
    t.column "valid_to",    :timestamp
  end

  add_index "computer_vulns", ["computer_id", "vuln_id"], :name => "INDEX_1"
  add_index "computer_vulns", ["vuln_id"], :name => "fk_reference_31"

  create_table "computers", :force => true do |t|
  end

  create_table "computers_contacts", :force => true do |t|
    t.column "computer_id",                   :integer, :limit => 20, :null => false
    t.column "contact_id",                    :integer, :limit => 8,  :null => false
    t.column "computer_relationship_type_id", :integer, :limit => 3,  :null => false
  end

  add_index "computers_contacts", ["contact_id"], :name => "fk_reference_85"
  add_index "computers_contacts", ["computer_id"], :name => "fk_reference_86"
  add_index "computers_contacts", ["computer_relationship_type_id"], :name => "fk_reference_87"

  create_table "computers_datasources", :force => true do |t|
    t.column "computer_id",            :integer, :limit => 20, :null => false
    t.column "datasource_id",          :integer, :limit => 5,  :null => false
    t.column "datasource_computer_id", :integer, :limit => 20, :null => false
  end

  add_index "computers_datasources", ["computer_id", "datasource_id"], :name => "ak_key_2", :unique => true
  add_index "computers_datasources", ["datasource_id", "datasource_computer_id"], :name => "ak_key_3", :unique => true

  create_table "computers_operating_systems", :force => true do |t|
    t.column "computer_id",         :integer,   :limit => 20, :null => false
    t.column "operating_system_id", :integer,   :limit => 5,  :null => false
    t.column "valid_from",          :timestamp,               :null => false
    t.column "valid_to",            :timestamp
  end

  add_index "computers_operating_systems", ["computer_id", "operating_system_id"], :name => "INDEX_1"
  add_index "computers_operating_systems", ["operating_system_id"], :name => "fk_reference_32"

  create_table "computers_property_1_values", :force => true do |t|
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "property_value_id", :integer,   :limit => 8,  :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp,               :null => false
  end

  add_index "computers_property_1_values", ["computer_id", "property_value_id"], :name => "INDEX_1"
  add_index "computers_property_1_values", ["property_value_id"], :name => "fk_reference_17"

  create_table "computers_property_2_values", :force => true do |t|
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "property_value_id", :integer,   :limit => 8,  :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp,               :null => false
  end

  add_index "computers_property_2_values", ["computer_id", "property_value_id"], :name => "INDEX_1"
  add_index "computers_property_2_values", ["property_value_id"], :name => "fk_reference_20"

  create_table "computers_property_3_values", :force => true do |t|
    t.column "computer_id",       :integer,   :limit => 20, :null => false
    t.column "property_value_id", :integer,   :limit => 8,  :null => false
    t.column "valid_from",        :timestamp,               :null => false
    t.column "valid_to",          :timestamp,               :null => false
  end

  add_index "computers_property_3_values", ["computer_id", "property_value_id"], :name => "INDEX_1"
  add_index "computers_property_3_values", ["property_value_id"], :name => "fk_reference_21"

  create_table "contacts", :force => true do |t|
    t.column "user_id", :integer, :limit => 8
    t.column "vcard",   :text,                 :default => "", :null => false
  end

  add_index "contacts", ["user_id"], :name => "fk_reference_82"

  create_table "cvss_metric_groups", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "cvss_metric_values", :force => true do |t|
    t.column "cvss_metric_id", :integer, :limit => 3,                 :null => false
    t.column "name",           :string,               :default => "", :null => false
    t.column "description",    :text,                 :default => "", :null => false
    t.column "score",          :float,                                :null => false
  end

  create_table "cvss_metrics", :force => true do |t|
    t.column "name",                 :string,               :default => "", :null => false
    t.column "description",          :text,                 :default => "", :null => false
    t.column "cvss_metric_group_id", :integer, :limit => 3,                 :null => false
  end

  create_table "dashboard_dashboard_widgets", :force => true do |t|
    t.column "dashboard_id",        :integer, :limit => 20,                :null => false
    t.column "dashboard_widget_id", :integer, :limit => 20,                :null => false
    t.column "position",            :integer, :limit => 3,  :default => 1, :null => false
  end

  create_table "dashboard_layouts", :force => true do |t|
    t.column "rows",        :integer, :limit => 3,                 :null => false
    t.column "cols",        :integer, :limit => 3,                 :null => false
    t.column "layout_data", :text,                 :default => "", :null => false
  end

  create_table "dashboard_widgets", :force => true do |t|
    t.column "visualization_type_id",      :integer, :limit => 3,                 :null => false
    t.column "user_id",                    :integer, :limit => 8,                 :null => false
    t.column "name",                       :string,               :default => "", :null => false
    t.column "description",                :text
    t.column "visualization_type_options", :text,                 :default => "", :null => false
  end

  create_table "dashboards", :force => true do |t|
    t.column "user_id",             :integer, :limit => 8,                 :null => false
    t.column "name",                :string,               :default => "", :null => false
    t.column "position",            :integer, :limit => 3, :default => 1,  :null => false
    t.column "dashboard_layout_id", :integer, :limit => 3,                 :null => false
  end

  create_table "datasource_computer_groups", :force => true do |t|
    t.column "datasource_computer_group_id", :integer, :limit => 20,                 :null => false
    t.column "datasource_id",                :integer, :limit => 6,                  :null => false
    t.column "name",                         :string,                :default => "", :null => false
  end

  add_index "datasource_computer_groups", ["datasource_computer_group_id", "datasource_id"], :name => "index_1", :unique => true

  create_table "datasource_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "datasources", :force => true do |t|
    t.column "name",               :string,               :default => "", :null => false
    t.column "datasource_type_id", :integer, :limit => 3,                 :null => false
    t.column "connection_params",  :text,                 :default => "", :null => false
  end

  add_index "datasources", ["datasource_type_id"], :name => "fk_reference_88"

  create_table "dlp_rules", :force => true do |t|
    t.column "name",            :string,               :default => "", :null => false
    t.column "dlp_severity_id", :integer, :limit => 3,                 :null => false
  end

  add_index "dlp_rules", ["dlp_severity_id"], :name => "fk_reference_72"

  create_table "dlp_severities", :force => true do |t|
    t.column "name",   :string, :default => "", :null => false
    t.column "weight", :float,                  :null => false
  end

  create_table "malware_statuses", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "malware_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "malwares", :force => true do |t|
    t.column "malware_type_id", :integer, :limit => 3,                 :null => false
    t.column "name",            :string,               :default => "", :null => false
    t.column "description",     :text
  end

  create_table "metric_thresholds", :force => true do |t|
    t.column "threshold",         :float,                :null => false
    t.column "report_metric_id",  :integer, :limit => 5, :null => false
    t.column "computer_group_id", :integer, :limit => 5, :null => false
  end

  add_index "metric_thresholds", ["report_metric_id"], :name => "fk_reference_90"
  add_index "metric_thresholds", ["computer_group_id"], :name => "fk_reference_91"

  create_table "operating_systems", :force => true do |t|
    t.column "name",      :string,               :default => "", :null => false
    t.column "parent_id", :integer, :limit => 5
  end

  create_table "operating_systems_bes", :force => true do |t|
    t.column "operating_system_id", :integer, :limit => 20,                  :null => false
    t.column "pattern",             :string,  :limit => 512, :default => "", :null => false
  end

  add_index "operating_systems_bes", ["operating_system_id", "pattern"], :name => "ak_key_2"

  create_table "platforms", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "properties", :force => true do |t|
    t.column "name",               :text,                 :default => "",    :null => false
    t.column "property_type_id",   :integer, :limit => 3,                    :null => false
    t.column "datasource_type_id", :integer, :limit => 3,                    :null => false
    t.column "is_default",         :boolean,              :default => false, :null => false
    t.column "is_enum",            :boolean,              :default => false, :null => false
  end

  create_table "property_1_values", :force => true do |t|
    t.column "value", :string, :default => "", :null => false
  end

  create_table "property_2_values", :force => true do |t|
    t.column "value", :string, :default => "", :null => false
  end

  create_table "property_3_values", :force => true do |t|
    t.column "value", :string, :default => "", :null => false
  end

  create_table "property_type_operators", :force => true do |t|
    t.column "name",             :string,               :default => "", :null => false
    t.column "property_type_id", :integer, :limit => 3,                 :null => false
  end

  create_table "property_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "remediation_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "report_delta_events", :force => true do |t|
    t.column "report_delta_type_id", :integer,   :limit => 3,                  :null => false
    t.column "instance_id",          :integer,   :limit => 20
    t.column "value",                :string,                  :default => "", :null => false
    t.column "time_stamp",           :timestamp,                               :null => false
  end

  add_index "report_delta_events", ["report_delta_type_id"], :name => "fk_reference_55"

  create_table "report_delta_types", :force => true do |t|
    t.column "name",      :string, :default => "", :null => false
    t.column "threshold", :float
  end

  create_table "report_delta_types_report_subjects", :id => false, :force => true do |t|
    t.column "report_subject_id",    :integer, :limit => 4, :null => false
    t.column "report_delta_type_id", :integer, :limit => 4, :null => false
  end

  add_index "report_delta_types_report_subjects", ["report_delta_type_id"], :name => "fk_reference_54"

  create_table "report_metrics", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "report_metrics_report_subjects", :id => false, :force => true do |t|
    t.column "report_metric_id",  :integer, :limit => 6, :null => false
    t.column "report_subject_id", :integer, :limit => 4, :null => false
    t.column "group_by",          :boolean,              :null => false
  end

  add_index "report_metrics_report_subjects", ["report_subject_id"], :name => "fk_reference_64"

  create_table "report_object_metrics", :force => true do |t|
    t.column "name",             :string,               :default => "", :null => false
    t.column "report_object_id", :integer, :limit => 3,                 :null => false
  end

  add_index "report_object_metrics", ["report_object_id"], :name => "FK_Reference_48"

  create_table "report_object_poi", :id => false, :force => true do |t|
    t.column "report_object_id", :integer, :limit => 4, :null => false
    t.column "report_poi_id",    :integer, :limit => 4, :null => false
  end

  add_index "report_object_poi", ["report_poi_id"], :name => "FK_Reference_54"

  create_table "report_object_properties", :force => true do |t|
    t.column "name",             :string,               :default => "", :null => false
    t.column "report_object_id", :integer, :limit => 3,                 :null => false
    t.column "property_type_id", :integer, :limit => 3,                 :null => false
  end

  add_index "report_object_properties", ["report_object_id"], :name => "FK_Reference_47"
  add_index "report_object_properties", ["property_type_id"], :name => "FK_Reference_49"

  create_table "report_objects", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "report_poi", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "report_poi_data", :force => true do |t|
    t.column "report_poi_id", :integer,   :limit => 3,                  :null => false
    t.column "time_stamp",    :timestamp,                               :null => false
    t.column "value",         :string,                  :default => "", :null => false
    t.column "instance_id",   :integer,   :limit => 20
  end

  add_index "report_poi_data", ["report_poi_id"], :name => "FK_Reference_55"

  create_table "report_subject_properties", :force => true do |t|
    t.column "name",              :string,               :default => "",    :null => false
    t.column "report_subject_id", :integer, :limit => 3,                    :null => false
    t.column "property_type_id",  :integer, :limit => 3,                    :null => false
    t.column "select_clause",     :string
    t.column "ar_class",          :string
    t.column "is_aggregate",      :boolean,                                 :null => false
    t.column "is_default",        :boolean,                                 :null => false
    t.column "is_enum",           :boolean,              :default => false, :null => false
  end

  create_table "report_subjects", :force => true do |t|
    t.column "name",        :string, :default => "", :null => false
    t.column "name_plural", :string, :default => "", :null => false
    t.column "table_name",  :string, :default => "", :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name",  :string,  :default => "",    :null => false
    t.column "admin", :boolean, :default => false, :null => false
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :limit => 8, :null => false
    t.column "user_id", :integer, :limit => 8, :null => false
  end

  add_index "roles_users", ["user_id"], :name => "fk_reference_79"

  create_table "user_temp_tables", :force => true do |t|
    t.column "user_id",         :integer, :limit => 8,                  :null => false
    t.column "session_id",      :string,  :limit => 32, :default => "", :null => false
    t.column "table_arguments", :text
    t.column "table_name",      :string,  :limit => 64, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",                      :string,    :limit => 200, :default => "", :null => false
    t.column "email",                     :string,    :limit => 200, :default => "", :null => false
    t.column "hashed_password",           :string,    :limit => 40,  :default => "", :null => false
    t.column "username",                  :string,    :limit => 200, :default => "", :null => false
    t.column "remember_token_expires_at", :timestamp
    t.column "remember_token",            :string,    :limit => 40
    t.column "salt",                      :string,    :limit => 40,  :default => "", :null => false
  end

  add_index "users", ["email"], :name => "ak_key_2", :unique => true
  add_index "users", ["username"], :name => "ak_key_3", :unique => true

  create_table "visualization_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "vuln_advisories", :force => true do |t|
    t.column "vuln_id",                    :integer, :limit => 5,                  :null => false
    t.column "vuln_advisory_publisher_id", :integer, :limit => 3,                  :null => false
    t.column "advisory_id",                :string,  :limit => 20, :default => "", :null => false
  end

  add_index "vuln_advisories", ["vuln_id", "vuln_advisory_publisher_id"], :name => "INDEX_1"
  add_index "vuln_advisories", ["vuln_advisory_publisher_id"], :name => "fk_reference_38"

  create_table "vuln_advisory_publishers", :force => true do |t|
    t.column "name",       :string, :default => "", :null => false
    t.column "url_prefix", :string, :default => "", :null => false
    t.column "url_suffix", :string
  end

  create_table "vuln_cvss_metric_values", :id => false, :force => true do |t|
    t.column "vuln_id",              :integer, :limit => 5, :null => false
    t.column "cvss_metric_value_id", :integer, :limit => 3, :null => false
  end

  add_index "vuln_cvss_metric_values", ["cvss_metric_value_id"], :name => "fk_reference_43"

  create_table "vuln_remediations", :force => true do |t|
    t.column "remediation_type_id", :integer, :limit => 3,                 :null => false
    t.column "description",         :string,               :default => "", :null => false
    t.column "app_upgrade_id",      :integer, :limit => 5
  end

  add_index "vuln_remediations", ["app_upgrade_id"], :name => "fk_reference_75"

  create_table "vuln_remediations_vulns", :id => false, :force => true do |t|
    t.column "vuln_id",             :integer, :limit => 6, :null => false
    t.column "vuln_remediation_id", :integer, :limit => 9, :null => false
  end

  add_index "vuln_remediations_vulns", ["vuln_remediation_id"], :name => "fk_reference_66"

  create_table "vuln_risks", :force => true do |t|
    t.column "name", :text, :default => "", :null => false
  end

  create_table "vuln_severities", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "vulns", :force => true do |t|
    t.column "name",                     :string,               :default => "", :null => false
    t.column "description",              :text
    t.column "vuln_severity_id",         :integer, :limit => 3
    t.column "publish_date",             :date
    t.column "cvss_base_score",          :float
    t.column "cvss_temporal_score",      :float
    t.column "cvss_environmental_score", :float
    t.column "cvss_final_score",         :float
  end

  add_index "vulns", ["vuln_severity_id"], :name => "fk_reference_16"

  create_table "vulns_apps", :id => false, :force => true do |t|
    t.column "app_id",  :integer,              :null => false
    t.column "vuln_id", :integer, :limit => 5, :null => false
  end

  add_index "vulns_apps", ["vuln_id"], :name => "fk_reference_24"

  create_table "vulns_bes", :force => true do |t|
    t.column "vuln_id",     :integer, :limit => 20, :null => false
    t.column "fixlet_id",   :integer, :limit => 20, :null => false
    t.column "bes_site_id", :integer, :limit => 5,  :null => false
  end

  add_index "vulns_bes", ["vuln_id", "fixlet_id", "bes_site_id"], :name => "ak_key_2", :unique => true
  add_index "vulns_bes", ["bes_site_id"], :name => "fk_reference_102"

end
